services:
  spark:
    image: spark:3.5.7-python3
    container_name: spark
    ports:
      - "8081:8080"
    volumes:
      - ./dataset:/data/dataset
      - ./jobs:/data/jobs
      - ./data_lake:/data/data_lake
    command: ["bash", "-lc", "tail -f /dev/null"]
